name: Node.js CI 
on: 
  push: 
    branches:  
      - development   
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Use Node.js 12 
        uses: actions/setup-node@v1 
        with: 
          node-version: '12.x' 
      - run: npm ci 
      - run: npm t
      - run: npm run lint
